controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


users_list:
    path: /user
    controller: App\Controller\UsersController::usersList
    methods: GET

create_user:
    path: /user
    controller: App\Controller\UsersController::createUser
    methods: POST

delete_user:
    path: /user/{id}
    controller: App\Controller\UsersController::deleteUser
    methods: DELETE