controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


users_list:
    path: /user
    controller: App\Controller\UsersController::usersList
    methods: GET

show_user:
    path: /user/{id}
    controller: App\Controller\UsersController::showUser
    methods: GET

create_user:
    path: /user
    controller: App\Controller\UsersController::createUser
    methods: POST

delete_user:
    path: /user/{id}
    controller: App\Controller\UsersController::deleteUser
    methods: DELETE

# plan routes
plan_list:
    path: /plan
    controller: App\Controller\Plan\PlanController::planList
    methods: GET

show_plan:
    path: /plan/{id}
    controller: App\Controller\Plan\PlanController::showPlan
    methods: GET

create_plan:
    path: /plan
    controller: App\Controller\Plan\PlanController::createPlan
    methods: POST

edit_plan:
    path: /plan/{id}
    controller: App\Controller\Plan\PlanController::editPlan
    methods: PATCH

delete_plan:
    path: /plan/{id}
    controller: App\Controller\Plan\PlanController::deletePlan
    methods: DELETE

# users plan routes
create_user_plan:
    path: /plan/{plan_id}/users/{user_id}
    controller: App\Controller\Plan\PlanUserController::addUser
    methods: POST

